#!/bin/zsh

# Script must be ran as root.
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root"
    echo "Try 'sudo ./install'"
    exit 1
fi

echo "Installing the system tray onto your system..."

# Get the current working directory and the virtual environment
CWD=$(pwd)
ENV=$(pwd)/bin/activate
COMMAND="python $CWD/tray.py"

# Create the virtual environment and install the requirements
python -m venv .
source bin/activate
pip install -r requirements.txt

# Create the executable
sudo echo "#!/bin/zsh" > /usr/local/bin/tray
sudo echo "source $ENV" >> /usr/local/bin/tray
sudo echo "$COMMAND" >> /usr/local/bin/tray
sudo chmod +x /usr/local/bin/tray

echo "Done!"
