#!/bin/zsh

# Script must be ran as root.
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root"
    echo "Try 'sudo ./install'"
    exit 1
fi

# Check if the required packages are installed
echo "Checking for required packages..."

# Iterate through each line of the dependencies.txt file
# and check if the package is installed with check-dependency <command> <package>
while read -r line; do
    command=$(echo $line | awk -F ',' '{print $1}')
    package=$(echo $line | awk -F ',' '{print $2}')

    check-dependency $command $package

    if [[ $? -eq 1 ]]; then
        echo "The command $command from package $package could not be installed. Please install it before continuing."
        exit 1
    fi

done < dependencies.txt

echo "\nInstalling the system tray onto your system..."

# Get the current working directory and the virtual environment
CWD=$(pwd)
ENV=$(pwd)/bin/activate
COMMAND="python $CWD/tray.py"

# Create the virtual environment and install the requirements
python -m venv .
source bin/activate
pip install -r requirements.txt

# Create the executable
sudo echo "#!/bin/zsh" > /usr/local/bin/tray
sudo echo "source $ENV" >> /usr/local/bin/tray
sudo echo "$COMMAND" >> /usr/local/bin/tray
sudo chmod +x /usr/local/bin/tray

echo "Done!"
