#!/bin/zsh

# Script must be ran as root.
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root"
    echo "Try 'sudo ./install'"
    exit 1
fi

sudo rm /usr/local/bin/tray

cd ..
sudo rm -rf system-tray

echo "Done!"
